services:
  - type: web
    name: sampurna-manovikas-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://sampurnamanovikas.in
      - key: PORT
        value: 10000
    autoDeploy: true
