services:
  - type: web
    name: appointment-booking-api
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        fromService:
          type: web
          name: your-frontend-app
          property: url
    autoDeploy: true
    branch: main